#include <mkfmhdr.h>

#define FM_VERSION FM_MAKE_VERSION(1,04) /* V1.04 */
#define FM_SER_NO  0
#define FM_MANUFACTURER "SafeNet Inc"
#define FM_NAME "TESLA"

DEFINE_FM_HEADER(FM_NUMBER_CUSTOM_FM,
		FM_VERSION,
		FM_SER_NO,
		FM_MANUFACTURER,
		FM_NAME);
